name: Deploy feature branch to no production bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on:  ubuntu-latest
    env:
      BUCKET_NAME:  cfst-3457-ddf44106d75af23df9b4247d6-nonprodbucket-hmessfp63yct
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1
      - name: setup node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name:  build site
        run:  |
          npm ci
          npm run build
      - name: deploy files to bucket
        run:  aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read